name: WeChat Daily Checkin

on:
  # 每天北京时间 19 点自动运行
  schedule:
    - cron: "5 11 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 设置 Node.js 并启用 pnpm 缓存
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      # 恢复 config 缓存
      - name: Restore config cache
        uses: actions/cache@v3
        id: config-cache
        with:
          path: config.json
          key: config-${{ runner.os }}-latest

      # 写入或生成 config 文件（如果不存在）
      - name: Generate config
        run: |
          if [ ! -f config.json ]; then
            echo '{}' > config.json
          fi

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 运行 WeChat 签到脚本
      - name: Run WeChat checkin script
        env:
          APPID: ${{ secrets.APPID }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          IS_GITHUB_ACTIONS: ${{ secrets.IS_GITHUB_ACTIONS }}
        run: node index.js

      # 保存 config 缓存
      - name: Save config cache
        uses: actions/cache@v3
        with:
          path: config.json
          key: config-${{ runner.os }}-latest

      # 可选：查看 config
      - name: Show config
        run: cat config.json
