name: WeChat Daily Checkin

on:
  # 每天北京时间 19 点自动运行
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 恢复依赖缓存
      - name: Cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 运行 WeChat 签到脚本
      - name: Run WeChat checkin script
        env:
          NAME: ${{ secrets.NAME }}
          APPID: ${{ secrets.APPID }}
          REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
          REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}

        run: node main.js
