name: WeChat Daily Checkin

on:
  # 每天北京时间 19 点自动运行
  schedule:
    - cron: '5 11 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 恢复依赖缓存
      - name: Cache node_modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('package-lock.json', 'pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      # 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 运行 WeChat 签到脚本
      - name: Run WeChat checkin script
        env:
          APPID: ${{ secrets.APPID }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          IS_GITHUB_ACTIONS: true

        run: node index.js

      #部署到github
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
